#!/usr/bin/env bash
#
# Adapted from fzf installation script:
# https://github.com/junegunn/fzf

set -u

version=0.1.0
key_bindings=
update_config=2
shells="bash zsh fish nushell"
prefix='~/.fcd'
prefix_expand=~/.fcd
fish_dir=${XDG_CONFIG_HOME:-$HOME/.config}/fish
min_fzf_version=0.72.0

help() {
  cat << EOF
usage: $0 [OPTIONS]

    --help               Show this message
    --bin                Download fcd binary only; Do not generate ~/.fcd.{bash,zsh}
    --all                Download fcd binary and update configuration files
                         to enable key bindings
    --xdg                Generate files under \$XDG_CONFIG_HOME/fcd
    --[no-]key-bindings  Enable/disable key bindings (ALT-S, ALT-Q)
    --[no-]update-rc     Whether or not to update shell configuration files

    --no-bash            Do not set up bash configuration
    --no-zsh             Do not set up zsh configuration
    --no-fish            Do not set up fish configuration
    --no-nushell         Do not set up nushell configuration
EOF
}

for opt in "$@"; do
  case $opt in
    --help)
      help
      exit 0
      ;;
    --all)
      key_bindings=1
      update_config=1
      ;;
    --xdg)
      prefix='"${XDG_CONFIG_HOME:-$HOME/.config}"/fcd/fcd'
      prefix_expand=${XDG_CONFIG_HOME:-$HOME/.config}/fcd/fcd
      mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/fcd"
      ;;
    --key-bindings) key_bindings=1 ;;
    --no-key-bindings) key_bindings=0 ;;
    --update-rc) update_config=1 ;;
    --no-update-rc) update_config=0 ;;
    --bin) ;;
    --no-bash) shells=${shells/bash/} ;;
    --no-zsh) shells=${shells/zsh/} ;;
    --no-fish) shells=${shells/fish/} ;;
    --no-nushell) shells=${shells/nushell/} ;;
    *)
      echo "unknown option: $opt"
      help
      exit 1
      ;;
  esac
done


fail() {
  echo "$1"
  exit 1
}

# Ensure fzf is installed and has minimum version
echo -n "Checking fzf executable ... "
if ! command -v fzf > /dev/null; then
  echo 'Error: fzf executable not found'
  fail 'Please install fzf. Documentation: https://github.com/junegunn/fzf'
fi
fzf_version=$(FZF_DEFAULT_OPTS= command fzf --version 2>&1)
if [ $? -ne 0 ]; then
  echo "Error: $fzf_version"
  fail 'Installation failed.'
fi
fzf_version=${fzf_version/ */}
echo -n "$fzf_version "
if [ "$(printf '%s\n%s' "$min_fzf_version" "$fzf_version" | sort -V | head -n1)" != "$min_fzf_version" ]; then
  echo "(Error: requires >= $min_fzf_version)"
  fail 'Please update fzf. More info at: https://github.com/junegunn/fzf'
fi
echo "(OK)"
echo

cd "$(dirname "${BASH_SOURCE[0]}")"
fcd_base=$(pwd)
fcd_base_esc=$(printf %q "$fcd_base")

ask() {
  while true; do
    read -p "$1 ([y]/n) " -r
    REPLY=${REPLY:-"y"}
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      return 1
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
      return 0
    fi
  done
}

check_binary() {
  echo -n "  - Checking fcd executable ... "
  local output
  output=$(FCD_DEFAULT_OPTS= "$fcd_base"/bin/fcd --version 2>&1)
  if [ $? -ne 0 ]; then
    echo "Error: $output"
    binary_error="Invalid binary"
  else
    output=${output#* }
    if [ "$version" != "$output" ]; then
      echo "$output != $version"
      binary_error="Invalid version"
    else
      echo "$output (OK)"
      binary_error=""
      return 0
    fi
  fi
  rm -f "$fcd_base"/bin/fcd
  return 1
}

link_fcd_in_path() {
  if which_fcd="$(command -v fcd)"; then
    echo '  - Found in $PATH'
    echo "  - Creating symlink: bin/fcd -> $which_fcd"
    (cd "$fcd_base"/bin && rm -f fcd && ln -sf "$which_fcd" fcd)
    check_binary && return
  fi
  return 1
}

tar_opts="-xzf -"
if tar --no-same-owner -tf /dev/null 2> /dev/null; then
  tar_opts="--no-same-owner $tar_opts"
fi

try_curl() {
  command -v curl > /dev/null &&
    if [[ $1 =~ tar.gz$ ]]; then
      curl -fL $1 | tar $tar_opts
    else
      local temp=${TMPDIR:-/tmp}/fcd.zip
      curl -fLo "$temp" $1 && unzip -o "$temp" && rm -f "$temp"
    fi
}

try_wget() {
  command -v wget > /dev/null &&
    if [[ $1 =~ tar.gz$ ]]; then
      wget -O - $1 | tar $tar_opts
    else
      local temp=${TMPDIR:-/tmp}/fcd.zip
      wget -O "$temp" $1 && unzip -o "$temp" && rm -f "$temp"
    fi
}

download() {
  echo "Downloading bin/fcd ..."
  if [ -x "$fcd_base"/bin/fcd ]; then
    echo "  - Already exists"
    check_binary && return
  fi
  link_fcd_in_path && return
  mkdir -p "$fcd_base"/bin && cd "$fcd_base"/bin
  if [ $? -ne 0 ]; then
    binary_error="Failed to create bin directory"
    return
  fi

  local url
  url=https://github.com/matheus-pacifico/fcd/releases/download/v$version/${1}
  set -o pipefail
  if ! (try_curl $url || try_wget $url); then
    set +o pipefail
    binary_error="Failed to download with curl and wget"
    return
  fi
  set +o pipefail

  if [ ! -f fcd ]; then
    binary_error="Failed to download ${1}"
    return
  fi

  chmod +x fcd && check_binary
}

# Try to download binary executable
os_type=$(uname -s)
binary_available=1
binary_error=""
case "$os_type" in
  Linux) download fcd-${version}-linux.tar.gz ;;
  *) binary_available=0 binary_error=1 ;;
esac

cd "$fcd_base"
if [ -n "$binary_error" ]; then
  if [ $binary_available -eq 0 ]; then
    echo "No prebuilt binary for $os_type ..."
  else
    echo "  - $binary_error !!!"
  fi
  fail "Installation failed"
fi

[[ $* =~ "--bin" ]] && exit 0

for s in $shells; do
  bin=$s
  [[ $s == nushell ]] && bin=nu
  if ! command -v "$bin" > /dev/null; then
    shells=${shells/$s/}
  fi
done

if [[ -z ${shells// /} ]]; then
  echo "No shell configuration to be updated."
  exit 0
fi

# Key-bindings
if [ -z "$key_bindings" ]; then
  ask "Do you want to enable key bindings?"
  key_bindings=$?
fi

echo
for shell in $shells; do
  [[ $shell == nushell ]] && continue
  fcd_key_bindings="source \"$fcd_base/shell/key-bindings.${shell}\""
  [[ $shell == fish ]] && continue
  src=${prefix_expand}.${shell}
  echo -n "Generate $src ... "

  if [ $key_bindings -eq 0 ]; then
    fcd_key_bindings="# $fcd_key_bindings"
  fi

  cat > "$src" << EOF
# Setup fcd
# ---------
if [[ ! "\$PATH" == *$fcd_base_esc/bin* ]]; then
  PATH="\${PATH:+\${PATH}:}$fcd_base/bin"
fi

EOF

  cat >> "$src" << EOF
# Key bindings
# ------------
$fcd_key_bindings
EOF
  echo "OK"
done

# fish
if [[ $shells =~ fish ]]; then
  echo -n "Update fish_user_paths ... "
  fish << EOF
  echo \$fish_user_paths | \grep "$fcd_base"/bin > /dev/null
  or set --universal fish_user_paths \$fish_user_paths "$fcd_base"/bin
EOF
  [ $? -eq 0 ] && echo "OK" || echo "Failed"
fi

append_line() {
  local update line file pat lines
  update="$1"
  line="$2"
  file="$3"
  pat="${4:-}"
  at_lno="${5:-}"
  lines=""

  echo "Update $file:"
  echo "  - $line"
  if [ -f "$file" ]; then
    if [[ -n $pat ]]; then
      lines=$(\grep -nF "$pat" "$file")
    else
      lines=$(\grep -nF "${line#"${line%%[![:space:]]*}"}" "$file")
    fi
  fi

  if [ -n "$lines" ]; then
    echo "    - Already exists:"
    sed 's/^/        Line /' <<< "$lines"

    update=0
    if ! \grep -qv "^[0-9]*:[[:space:]]*#" <<< "$lines"; then
      echo "    - But they all seem to be commented"
      ask "    - Continue modifying $file?"
      update=$?
    fi
  fi

  set -e
  if [ "$update" -eq 1 ]; then
    if [[ -z $at_lno ]]; then
      [ -f "$file" ] && echo >> "$file"
      echo "$line" >> "$file"
    else
      sed -i.~fcd_bak "${at_lno}a\\"$'\n'"$line" "$file" && rm "$file.~fcd_bak"
    fi
    echo "    + Added"
  else
    echo "    ~ Skipped"
  fi

  echo
  set +e
}

create_file() {
  local file="$1"
  shift
  echo "Create $file:"
  for line in "$@"; do
    echo "    $line"
    echo "$line" >> "$file"
  done
  echo
}

if [ $update_config -eq 2 ]; then
  echo
  ask "Do you want to update your shell configuration files?"
  update_config=$?
fi
echo
for shell in $shells; do
  [[ $shell == fish ]] && continue
  [[ $shell == nushell ]] && continue
  [[ $shell == zsh ]] && dest=${ZDOTDIR:-~}/.zshrc || dest=~/.bashrc
  append_line $update_config "[ -f ${prefix}.${shell} ] && source ${prefix}.${shell}" "$dest" "${prefix}.${shell}"
done

if [[ $shells =~ fish ]]; then
  bind_file="${fish_dir}/functions/fish_user_key_bindings.fish"
  if [ ! -e "$bind_file" ]; then
    if [[ $key_bindings -eq 1 ]]; then
      mkdir -p "${fish_dir}/functions"
      create_file "$bind_file" \
        'function fish_user_key_bindings' \
        "  $fcd_key_bindings" \
        'end'
      lno_func=$(\grep -nF "function fish_user_key_bindings" "$bind_file" | sed 's/:.*//' | tr '\n' ' ')
    else
      lno_func=0
    fi
  else
    echo "Check $bind_file:"
    lno_func=$(\grep -nF "function fish_user_key_bindings" "$bind_file" | sed 's/:.*//' | tr '\n' ' ')
    if [[ -z $lno_func ]]; then
      echo -e "function fish_user_key_bindings\nend" >> "$bind_file"
      lno_func=$(\grep -nF "function fish_user_key_bindings" "$bind_file" | sed 's/:.*//' | tr '\n' ' ')
    fi
    lno_keys=$(\grep -nF "fcd_key_bindings" "$bind_file" | sed 's/:.*//' | tr '\n' ' ')
    if [[ -n $lno_keys ]]; then
      echo "  ** Found 'fcd_key_bindings' in line #$lno_keys"
      if [[ $key_bindings -eq 1 ]]; then
        echo "  ** You have to replace the line to '$fcd_key_bindings'"
      else
        echo "  ** You have to remove the line"
      fi
      echo
    else
      echo "  - Clear"
      echo
      if [[ $key_bindings -eq 1 ]]; then
        append_line $update_config "  $fcd_key_bindings" "$bind_file" "" "$lno_func"
      fi
    fi
  fi
fi

if [[ $shells =~ nushell ]]; then
  if [[ $key_bindings -eq 1 ]]; then
    echo "Setting up Nushell integration ..."
		nushell_autoload_dir=$(nu -c '$nu.user-autoload-dirs | first')
    mkdir -p "$nushell_autoload_dir"
    dest="$nushell_autoload_dir/_fcd_integration.nu"
    echo -n "  Generate $dest ... "
    cp "$fcd_base/shell/key-bindings.nu" "$dest"
    echo "OK"
    echo
  fi
fi

if [ $update_config -eq 1 ]; then
  echo 'Finished. Restart your shell or reload config file.'
  if [[ $shells =~ bash ]]; then
    echo -n '   source ~/.bashrc  # bash'
    echo
  fi
  [[ $shells =~ zsh ]] && echo "   source ${ZDOTDIR:-~}/.zshrc   # zsh"
  [[ $shells =~ fish && $lno_func -ne 0 ]] && echo '   fish_user_key_bindings  # fish'
  [[ $shells =~ nushell ]] && echo '   # nushell: files are loaded automatically from autoload directory'
  echo
  echo 'Use uninstall script to remove fcd.'
  echo
fi
echo 'For more information, see: https://github.com/matheus-pacifico/fcd'
